natalia7/config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
	
  get '/members_only', to: "static_pages#members_only"
  get '/admins_only', to: "static_pages#admins_only"
  passwordless_for :users
end

natalia7/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

natalia7/app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record? 

  def set_default_role
    self.role ||= :user
  end

  passwordless_with :email
end

natalia7/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
    def user_not_authorized
      flash[:error] = "You don't have access to this section."
      redirect_back(fallback_location: root_path)
    end
end

natalia7/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, except: [:home]

  def home
    @signed_in = :false #TODO: add current user method
  end

  def members_only
  end

  def admin_only
    if current_user.role != "admin" #doubt current_user.role returns anything meaningful
      flash[:notice] = "unauthorized"
      redirect_to root_path
    end

  end
end

natalia7/app/helpers/application_helper.rb
module ApplicationHelper
end

natalia7/app/helpers/application_helper.rb_helper.rb
module ApplicationHelper
end

natalia7/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

natalia7/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SignIn</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
 <nav>
  <ul>
    <li><%= link_to "home", root_path, :class => "active" %></li>
    <li><%= link_to "members", members_only_path %></li>
    <li><%= link_to "admin", admins_only_path %></li>
    <li><%= link_to "Sign Out", users.sign_out_path, method: :delete %></li>
    <li><%= link_to "Sign In", users.sign_in_path %></li>
  </ul>
</nav>
<div class="main-content">
  <div class="login-info">
    <p> you are signed in as current_user.email </p>
    <p> with role current_user.role </p>
  </div>
  <%= yield %>
</div>
</body>
</html>

natalia7/app/views/static_pages/admin_only.html.erb
<h1>StaticPages#admin_only</h1>
<p>Find me in app/views/static_pages/admin_only.html.erb</p>

natalia7/app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p> Is the user signed in? : <%= @signed_in ? "YES!" : "no :(" %> </p>

natalia7/app/views/static_pages/members_only.html.erb
<h1>StaticPages#members_only</h1>
<p>Find me in app/views/static_pages/members_only.html.erb</p>